/*
 * Gurjit Singh
 * Friday November 30th - 2019
 * This program displays the developing software for the Planet Zirboin
 */

/**
 *
 * @author sangha
 */
public class DevelopingSoftwareForPlanetZirboinfrm extends javax.swing.JFrame {

    /**
     * Creates new form DevelopingSoftwareForPlanetZirboinfrm
     */
    public DevelopingSoftwareForPlanetZirboinfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFirst = new javax.swing.JLabel();
        lblSecond = new javax.swing.JLabel();
        lblThird = new javax.swing.JLabel();
        lblFourth = new javax.swing.JLabel();
        lblFifth = new javax.swing.JLabel();
        lblSixth = new javax.swing.JLabel();
        lblSeventh = new javax.swing.JLabel();
        lblEighth = new javax.swing.JLabel();
        lblNinth = new javax.swing.JLabel();
        txtFirst = new javax.swing.JTextField();
        txtSecond = new javax.swing.JTextField();
        txtThird = new javax.swing.JTextField();
        txtFourth = new javax.swing.JTextField();
        txtFifth = new javax.swing.JTextField();
        txtSixth = new javax.swing.JTextField();
        txtSeventh = new javax.swing.JTextField();
        btnFirst = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFirst.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblFirst.setForeground(new java.awt.Color(255, 255, 0));
        lblFirst.setText("Bank Software for Planet Zirboin");
        jPanel1.add(lblFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 33, -1, -1));

        lblSecond.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        lblSecond.setForeground(new java.awt.Color(255, 255, 255));
        lblSecond.setText("Enter the number of vrobits to convert: ");
        jPanel1.add(lblSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        lblThird.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        lblThird.setForeground(new java.awt.Color(255, 255, 255));
        lblThird.setText("Vrobits:");
        jPanel1.add(lblThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        lblFourth.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        lblFourth.setForeground(new java.awt.Color(255, 255, 255));
        lblFourth.setText("Drobzits (100,000 vrobits):");
        jPanel1.add(lblFourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        lblFifth.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        lblFifth.setForeground(new java.awt.Color(255, 255, 255));
        lblFifth.setText("Clickwicks (50,000 Vrobits):");
        jPanel1.add(lblFifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        lblSixth.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        lblSixth.setForeground(new java.awt.Color(255, 255, 255));
        lblSixth.setText("Gazoontights (10,000 Vrobits):");
        jPanel1.add(lblSixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        lblSeventh.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        lblSeventh.setForeground(new java.awt.Color(255, 255, 255));
        lblSeventh.setText("Frazoints (1,000 Vrobits):");
        jPanel1.add(lblSeventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        lblEighth.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        lblEighth.setForeground(new java.awt.Color(255, 255, 255));
        lblEighth.setText("Blointoints (500 Vrobits):");
        jPanel1.add(lblEighth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        lblNinth.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        lblNinth.setForeground(new java.awt.Color(255, 255, 255));
        lblNinth.setText("Remaining Vrobits:");
        jPanel1.add(lblNinth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        txtFirst.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jPanel1.add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 100, -1));

        txtSecond.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jPanel1.add(txtSecond, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 100, -1));

        txtThird.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jPanel1.add(txtThird, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 100, -1));

        txtFourth.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jPanel1.add(txtFourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 100, -1));

        txtFifth.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jPanel1.add(txtFifth, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 100, -1));

        txtSixth.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jPanel1.add(txtSixth, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 100, -1));

        txtSeventh.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jPanel1.add(txtSeventh, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 100, -1));

        btnFirst.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        btnFirst.setText("Covert");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        jPanel1.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        double vrobits, drobzits, rmVrobits, clickwicks, rmVrobits2, gazoontights, rmVrobits3, frazoints, rmVrobits4, blointoints, rmVrobits5;
        
        vrobits = Double.parseDouble(txtFirst.getText()); // The user will write the number of vrobits in this text field
        
        drobzits = vrobits / 100000;
        drobzits = drobzits * 1; // Drobzits round up (line from 148 to 150)
        drobzits = Math.floor(drobzits);
        drobzits = drobzits / 1;
        rmVrobits = vrobits % 100000;
        
        clickwicks = rmVrobits / 50000;
        clickwicks = clickwicks * 1; // Drobzits round up (line from 154 to 156)
        clickwicks = Math.floor(clickwicks);
        clickwicks = clickwicks / 1;
        rmVrobits2 = vrobits % 50000;
        
        gazoontights = rmVrobits2 / 10000;
        gazoontights = gazoontights * 1; // Drobzits round up (line from 160 to 162)
        gazoontights = Math.floor(gazoontights);
        gazoontights = gazoontights / 1;
        rmVrobits3 = vrobits % 10000;
        
        frazoints = rmVrobits3 / 1000;
        frazoints = frazoints * 1; // Drobzits round up (line from 166 to 168)
        frazoints = Math.floor(frazoints);
        frazoints = frazoints / 1;
        rmVrobits4 = vrobits % 1000;
        
        blointoints = rmVrobits4 / 500;
        blointoints = blointoints * 1; // Drobzits round up (line from 172 to 174)
        blointoints = Math.floor(blointoints);
        blointoints = blointoints / 1;
        rmVrobits5 = vrobits % 500;
        
        txtSecond.setText(drobzits + "");
        txtThird.setText(clickwicks + "");
        txtFourth.setText(gazoontights + "");
        txtFifth.setText(frazoints + "");
        txtSixth.setText(blointoints + "");
        txtSeventh.setText(rmVrobits5 + "");
    }//GEN-LAST:event_btnFirstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevelopingSoftwareForPlanetZirboinfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevelopingSoftwareForPlanetZirboinfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevelopingSoftwareForPlanetZirboinfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevelopingSoftwareForPlanetZirboinfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevelopingSoftwareForPlanetZirboinfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEighth;
    private javax.swing.JLabel lblFifth;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblFourth;
    private javax.swing.JLabel lblNinth;
    private javax.swing.JLabel lblSecond;
    private javax.swing.JLabel lblSeventh;
    private javax.swing.JLabel lblSixth;
    private javax.swing.JLabel lblThird;
    private javax.swing.JTextField txtFifth;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtFourth;
    private javax.swing.JTextField txtSecond;
    private javax.swing.JTextField txtSeventh;
    private javax.swing.JTextField txtSixth;
    private javax.swing.JTextField txtThird;
    // End of variables declaration//GEN-END:variables
}
